findfile,tgrep: look in /usr/local/bin first for executables

diff --git a/bin/findfile b/bin/findfile
--- a/bin/findfile
+++ b/bin/findfile
@@ -7,16 +7,16 @@
 # The first parameter is the executable filename.
 # The second parameter is a variable that will hold the absolute pathname.
 locate_exe() {
-  if [ -x /usr/bin/$1 ]; then
-    eval "$2=/usr/bin/$1"
-  elif [ -x /bin/$1 ]; then
-    eval "$2=/bin/$1"
-  elif [ -x /usr/local/bin/$1 ]; then
-    eval "$2=/usr/local/bin/$1"
-  else
-    echo "ERROR: Unable to locate the '$1' program."
-    exit 2
-  fi
+    if [ -x /usr/local/bin/$1 ]; then
+        eval "$2=/usr/local/bin/$1"
+    elif [ -x /usr/bin/$1 ]; then
+        eval "$2=/usr/bin/$1"
+    elif [ -x /bin/$1 ]; then
+        eval "$2=/bin/$1"
+    else
+        echo "ERROR: Unable to locate the '$1' program."
+        exit 2
+    fi
 }
 
 # Locate executables.
