pycheck: add --single,--help options

diff --git a/bin/pycheck b/bin/pycheck
--- a/bin/pycheck
+++ b/bin/pycheck
@@ -3,7 +3,44 @@
 # Runs multiple Python static checkers.
 #
 
-FILE=$1
+# Process command line.
+SINGLE=false
+FILE=""
+FOUND=false
+while [ "$1" != "" ]; do
+    case $1 in
+        -h|-?|--help)
+            echo "Usage: `basename $0` [options] FILE" >&2
+            echo "  Runs multiple Python static checkers." >&2
+            echo "" >&2
+            echo "Options:" >&2
+            echo "  -h, --help            show this help message and exit" >&2
+            echo "  --single              only run first checker found" >&2
+            exit 1
+            ;;
+        --single)
+            SINGLE=true
+            ;;
+        -*)
+            echo "ERROR: Unknown option $1" >&2
+            exit 1
+            ;;
+        *)
+            if [ "${FILE}" = "" ]; then
+                FILE=$1
+            else
+                echo "ERROR: To many args" >&2
+                exit 1
+            fi
+            ;;
+    esac
+    shift
+done
+
+if [ "${FILE}" = "" ]; then
+    echo "ERROR: FILE not specified" >&2
+    exit 1
+fi
 
 checkpath() {
     # Return True if $1 is in ${PATH}.
@@ -16,40 +53,10 @@ checkpath() {
     return 1
 }
 
-if checkpath pep8; then
-    echo "## pep8"
-    # E202 whitespace before ')'
-    pep8 --ignore=E202 --repeat ${FILE}
-else
-    echo "## pep8 not installed"
-fi
-
-if checkpath pyflakes; then
-    echo "## pyflakes"
-    pyflakes ${FILE}
-else
-    echo "## pyflakes not installed"
-fi
-
-if checkpath pychecker; then
-    # pychecker raises an ImportError if the file does not end in ".py".
-    if [ ${FILE%.py} != ${FILE} ]; then
-        echo "## pychecker"
-        # --maxargs cannot be specified in ~/.pycheckrc
-        pychecker --maxargs=20 --limit=200 --quiet ${FILE}
-        # Cleanup generated bytecode file.
-        if [ -f ${FILE}c ]; then
-            rm ${FILE}c
-        fi
-    else
-        echo "## pychecker not run because input file does not have .py suffix."
-    fi
-else
-    echo "## pychecker not installed"
-fi
-
 if checkpath pylint; then
-    echo "## pylint"
+    if ! ${SINGLE}; then
+        echo "## pylint"
+    fi
     pylint\
         --profile=no\
         --persistent=no\
@@ -57,6 +64,65 @@ if checkpath pylint; then
         --include-ids=yes\
         --reports=no\
         ${FILE}
-else
+    if ${SINGLE}; then
+        exit
+    fi
+    FOUND=true
+elif ! ${SINGLE}; then
     echo "## pylint not installed"
+fi
+
+if checkpath pychecker; then
+    # pychecker raises an ImportError if the file does not end in ".py".
+    if [ ${FILE%.py} != ${FILE} ]; then
+        if ! ${SINGLE}; then
+            echo "## pychecker"
+        fi
+        # --maxargs cannot be specified in ~/.pycheckrc
+        pychecker --maxargs=20 --limit=200 --quiet ${FILE}
+        # Cleanup generated bytecode file.
+        if [ -f ${FILE}c ]; then
+            rm ${FILE}c
+        fi
+        if ${SINGLE}; then
+            exit
+        fi
+        FOUND=true
+    else
+        echo "## pychecker not run because input file does not have .py suffix."
+    fi
+elif ! ${SINGLE}; then
+    echo "## pychecker not installed"
+fi
+
+if checkpath pyflakes; then
+    if ! ${SINGLE}; then
+        echo "## pyflakes"
+    fi
+    pyflakes ${FILE}
+    if ${SINGLE}; then
+        exit
+    fi
+    FOUND=true
+elif ! ${SINGLE}; then
+    echo "## pyflakes not installed"
+fi
+
+if checkpath pep8; then
+    if ! ${SINGLE}; then
+        echo "## pep8"
+    fi
+    # E202 whitespace before ')'
+    pep8 --ignore=E202 --repeat ${FILE}
+    if ${SINGLE}; then
+        exit
+    fi
+    FOUND=true
+elif ! ${SINGLE}; then
+    echo "## pep8 not installed"
+fi
+
+if ! ${FOUND}; then
+    echo "ERROR: No Python static checker found." >&2
+    exit 1
 fi
